import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

export const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});
export const charter = localFont({
  src: [
    {
      path: "../../public/fonts/charter.otf",
      weight: "400",
      style: "normal",
    }
  ],
  variable: "--font-charter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${charter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
