import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

export const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});
export const charter = localFont({
  src: [
    {
      path: "../../public/fonts/charter.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-charter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon-new.ico",
    shortcut: "/favicon-96x96-new.png",
    apple: "/apple-touch-icon-new.png",
    other: [
      {
        rel: "icon",
        url: "/favicon-new.svg",
        type: "image/svg+xml",
      },
    ],
  },
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon-new.ico" sizes="any" />
        <link rel="icon" href="/favicon-new.svg" type="image/svg+xml" />
        <link rel="apple-touch-icon" href="/apple-touch-icon-new.png" />
        <link rel="manifest" href="/manifest.json" />
      </head>
      <body className={`${inter.variable} ${charter.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
